### ISSUE TITLE
Running into a Segmentation fault upon server startup

### ISSUE THREAD

**Issue by nl-saw** [noisiver/mod-junk-to-gold#3]
![image](https://github.com/user-attachments/assets/585268bc-eef6-4717-91fc-7d7525da5ae4)

On execute of  `player->DestroyItem(item->GetBagSlot(), item->GetSlot(), true);`

https://github.com/noisiver/mod-junk-to-gold/blob/5aa77a8dcc10e8b3ee9db0b242eba8442e83a1d5/src/mod_junk_to_gold.cpp#L21

I don't think its an issue with this mod, yet it is interesting it only happens when I have this mod enabled.
My attempts to fix it in any way were less than fruitful.

**Comment by noisiver** [comment]
The reason for this is that the item it's trying to destroy has already been destroyed (or moved) so the object doesn't exist anymore. I know some people had issues with this in the past because another mod was messing with items (changing them or something) and it changed the object and junk-to-gold tried to access the "old" item and it crashed.

I have spent some time trying to fix it, to stop it from crashing, but I don't understand how it could crash when there is a check to make sure the item exists etc.

**Comment by noisiver** [comment]
It would be nice to fix it. I have never heard of the server crashing on startup by the way, just when they loot stuff. In fact, it uses OnLootItem so it couldn't do that. It must be the bots looting something, right?

One thing I seem to remember is aoe-loot causing conflicts with this, if I'm not mistaken. I don't know what you're using though.
